---
- hosts: k8s-cluster
  vars:
    os: Debian_11
    kube_version: '1.23'
    pgp_location: /usr/share/keyrings
    release_pgp: libcontainers-archive-keyring.gpg
    crio_pgp: libcontainers-crio-archive-keyring.gpg
    crio_download_url: 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:'
  tasks:
    - name: Add container release to apt
      ansible.builtin.shell:
        cmd: >
          echo "deb [signed-by={{ pgp_location }}/{{ release_pgp }}] {{ crio_download_url }}/stable/{{ os }}/ /" >
          /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list

    - name: Add container crio release to apt
      ansible.builtin.shell:
        cmd: >
          echo "deb [signed-by={{ pgp_location }}/{{ crio_pgp }}] {{ crio_download_url }}/stable:/cri-o:/{{ kube_version }}/{{ os }}/ /" >
          /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:{{ kube_version }}.list

    - name: Get container release pgp
      ansible.builtin.shell:
        cmd: >
          curl -L {{ crio_download_url }}/stable/{{ os }}/Release.key |
          gpg --dearmor -o {{ pgp_location }}/{{ release_pgp }}
      register: download_pgp
      failed_when: download_pgp.rc != 0

    - name: Get crio container release pgp
      ansible.builtin.shell:
        cmd: >
          curl -L {{ crio_download_url }}/stable:/crio:/{{ kube_version }}/{{ os }}/Release.key |
          gpg --dearmor -o {{ pgp_location }}/{{ crio_pgp }}
      register: download_pgp
      failed_when: download_pgp.rc != 0

    - name: Install relevant crio
      ansible.builtin.apt:
        name:
          - cri-o
          - cri-o-runc
        state: present
        update_cache: yes

    - name: Reload systemd unit
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable crio at startup
      ansible.builtin.systemd:
        name: crio
        state: started
        enabled: yes